// Code generated by protoc-gen-go.
// source: PageGetter.proto
// DO NOT EDIT!

/*
Package PageGetter is a generated protocol buffer package.

It is generated from these files:
	PageGetter.proto

It has these top-level messages:
	Request
	Result
*/
package PageGetter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Result struct {
	Pageids []string `protobuf:"bytes,1,rep,name=pageids" json:"pageids,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetPageids() []string {
	if m != nil {
		return m.Pageids
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Result)(nil), "Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for PageGetter service

type PageGetterClient interface {
	GetPagesFromQuery(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error)
}

type pageGetterClient struct {
	c           client.Client
	serviceName string
}

func NewPageGetterClient(serviceName string, c client.Client) PageGetterClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pagegetter"
	}
	return &pageGetterClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *pageGetterClient) GetPagesFromQuery(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.serviceName, "PageGetter.GetPagesFromQuery", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PageGetter service

type PageGetterHandler interface {
	GetPagesFromQuery(context.Context, *Request, *Result) error
}

func RegisterPageGetterHandler(s server.Server, hdlr PageGetterHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PageGetter{hdlr}, opts...))
}

type PageGetter struct {
	PageGetterHandler
}

func (h *PageGetter) GetPagesFromQuery(ctx context.Context, in *Request, out *Result) error {
	return h.PageGetterHandler.GetPagesFromQuery(ctx, in, out)
}

func init() { proto.RegisterFile("PageGetter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x48, 0x4c, 0x4f,
	0x75, 0x4f, 0x2d, 0x29, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe7, 0x62,
	0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x2c, 0x4d, 0x2d, 0xaa,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x94, 0xb8, 0xd8, 0x82, 0x52, 0x8b,
	0x4b, 0x73, 0x4a, 0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0xd3, 0x53, 0x33, 0x53, 0x8a, 0x25, 0x18,
	0x15, 0x98, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x23, 0x33, 0x2e, 0x2e, 0x84, 0xc1, 0x42, 0x1a, 0x5c,
	0x82, 0xee, 0xa9, 0x25, 0x20, 0x81, 0x62, 0xb7, 0xa2, 0xfc, 0xdc, 0x40, 0x90, 0x31, 0x42, 0x1c,
	0x7a, 0x50, 0x6b, 0xa4, 0xd8, 0xf5, 0x20, 0xe6, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xdd, 0x60, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x65, 0xd5, 0x06, 0x11, 0x97, 0x00, 0x00, 0x00,
}
